/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "classes": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "private": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "public": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
